enum Constants {
  GET_CATEGORIES_REQUESTED = "GET_CATEGORIES_REQUESTED",
  GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS",
  GET_CATEGORIES_FAILED = "GET_CATEGORIES_FAILED",
}

export default Constants;
